import 'package:flutter/material.dart';

// Main Color
const THOR_COLOR_PRIMARY_YELLOW = Color(0xFFF1D375);
const THOR_COLOR_PRIMARY_GREY = Color(0xFF6F5F5E);
const THOR_COLOR_SECONDARY_BLUE = Color(0xFF1094FB);
const THOR_COLOR_SECONDARY_PINK = Color(0xFFFF037A);

// General Color
const THOR_COLOR_RED = Color(0xFFDB3B21);
const THOR_COLOR_GREEN = Color(0xFF1AAA55);
const THOR_COLOR_ORANGE = Color(0xFFFC9403);
const THOR_COLOR_WHITE = Color(0xFFFFFFFF);
const THOR_COLOR_BLACK = Color(0xFF2C2626);
const THOR_COLOR_BROWN = Color(0xFF493939);
const THOR_COLOR_BLUE = Color(0xFF1094FB);
const THOR_COLOR_GREY = Color(0xFFF0F0F0);

// Greyscale Color
const THOR_COLOR_GREYSACLE_500 = Color(0xFF888888);
const THOR_COLOR_GREYSCALE_400 = Color(0xFFA89D9D);
const THOR_COLOR_GREYSCALE_300 = Color(0xFFA4A8AD);
const THOR_COLOR_GREYSCALE_200 = Color(0xFFDEDEDE);
const THOR_COLOR_GREYSCALE_100 = Color(0xFFEFEFEF);

// Opacity
const THOR_OPACITY_LOW = 0.2;

// Spacing
const THOR_SPACE_BASE = 16.0;
const THOR_SPACE_LARGE = 24.0;
const THOR_SPACE_SMALL = 8.0;

const THOR_FONT_FAMILY = ["Mitr"];
// Corner Radius
const THOR_CORNER_RADIUS_LOW = 8.0;
const THOR_CORNER_RADIUS_MEDIUM = 12.0;
const THOR_CORNER_RADIUS_HIGH = 20.0;

// Font size
const THOR_FONT_SIZE_HEADLINE_1 = 36.0;
const THOR_FONT_SIZE_HEADLINE_2 = 22.0;
const THOR_FONT_SIZE_HEADLINE_5 = 18.0;
const THOR_FONT_SIZE_LARGE = 16.0;
const THOR_FONT_SIZE_BASE = 14.0;
const THOR_FONT_SIZE_CAPTION = 12.0;
const THOR_FONT_SIZE_OVERLINE = 10.0;

const THOR_FONT_WEIGHT_REGULAR = FontWeight.w400;
const THOR_FONT_WEIGHT_MEDIUM = FontWeight.w500;
const THOR_FONT_WEIGHT_BOLD = FontWeight.w700;
